<?php

namespace App\Providers;

use Illuminate\Database\Connection;
use Illuminate\Support\ServiceProvider;

class RickServiceProvider extends ServiceProvider
{

    /**
     * 延迟提供程序的加载
     *
     */
    public $defer = true;
    public function provides()
    {
        // TODO: Change the autogenerated stub
        return [Connection::class];
    }


    /**
     * Bootstrap the application services.
     *
     * @return void
     */
    public function boot()
    {
        //
    }

    /**
     * Register the application services.
     *
     * @return void
     */
    public function register()
    {
        //在 register 方法中，您只能将事务绑定到 服务容器 。
        //不应该在 register 方法中尝试注册任何事件监听器，路由或者任何其他功能。
        //否则，您可能会意外的使用到尚未加载的服务提供者提供的服务。

        /**
         * 在容器中注册绑定
         *
         */
        $this->app->singleton(Connection::class, function($app){
            return new Connection($app['config']['riak']);
        });

    }
}
